Description: >
  Creates an agency to deploy app with ansible

Parameters:
  WorkflowId:
    Description: An workflowID that will be prefixed to resources
    Default: CPROJECT
    Type: String
  SSHKeyName:
    Description: SSH key for agency access
    Default: udacity-devops-ec2
    Type: String
  amiImageId:
    Description: Defines the Image-ID of the OS to deploy
    Default: ami-0767046d1677be5a0
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${WorkflowId}-agency-SG
      GroupDescription: Allow port 22 for agency
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  agencyHost1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: !Ref SSHKeyName
      ImageId: !Ref amiImageId
      Tags:
        - Key: Name
          Value: !Sub ${WorkflowId}-agency
        - Key: Project
          Value: !Ref WorkflowId


