Description: >
  Creates an Amazon EKS Cluster
Parameters:
  WORKFLOW_ID:
    Description: An workflowID that will be prefixed to resources
    Default: CPROJECT
    Type: String

Resources:
  ClusterInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${WORKFLOW_ID}-cluster-profile
      Path: "/"
      Roles:
        - !Ref EKSClusterRole

  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${WORKFLOW_ID}-cluster-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess

  CapstoneProjectCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Version: "1.19"
      Name: !Sub ${WORKFLOW_ID}-cluster
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${WORKFLOW_ID}-SCG
        SubnetIds:
          Fn::Split:
            - ","
            - Fn::ImportValue:
                Fn::Sub: ${WORKFLOW_ID}-PUB-NETS
Outputs:
  EksId:
    Description: EKS id
    Value: !Ref CapstoneProjectCluster
    Export:
      Name: !Sub ${WORKFLOW_ID}-EKSCluster

  EKSRoleArn:
    Description: Role for accessing and creating aws resources
    Value: !GetAtt EKSClusterRole.Arn
    Export:
      Name: !Sub ${WORKFLOW_ID}-EKSRole
