---
- name: "Get LoadBalancer's DNS name "
  hosts: agency
  user: ubuntu
  gather_facts: false
  become: yes
  tasks:
    - name: Get the LoadBalancer's DNS name
      shell: "kubectl get svc capstone-project-service"
      register: elb_dns
      args:
        chdir: $HOME

    - name: Copy the output to a local file
      copy:
        content: "{{ elb_dns.stdout }}"
        dest: "~/elb_dns.txt"
      delegate_to: localhost
